=== sakss-g/xml/catalog_20049006.xsd
<?xml version="1.0"?>

<!--schema declaration-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified" >
    <xs:element name="august_gift_store">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="store_header"/>
                <xs:element ref="store_details"/>
                <xs:element ref="brand_collaboration"/>
                <xs:element ref="brands"/>
                <xs:element ref="gift_cards"/>
                <xs:element ref="page_footer"/>
                <xs:element ref="footer_info"/>
            </xs:sequence>
        </xs:complexType>    
    </xs:element>

    <!--child element of august_gift_store-->
    <xs:element name="store_header">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="store_logo"/>
                <xs:element ref="nav_bar"/>
                <xs:element ref="sign_in"/>
                <xs:element ref="search_bar"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!--child element of store_header-->
    <xs:element name="store_logo">
        <xs:complexType>
            <xs:attribute ref="id" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:attribute name="id" type="xs:ID"/> 
    <!--child element of store_header-->
    <xs:element name="nav_bar">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nav_element" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element ref="shopping_cart"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!--child element of nav_bar-->
    <xs:element name="nav_element" type="xs:string"/>
    <!--child element of nav_bar-->
    <xs:element name="shopping_cart">
        <xs:complexType>
            <xs:attribute ref="id" use="required"/>
        </xs:complexType>
    </xs:element>

    <!--child element of store_header-->
    <xs:element name="sign_in" type="xs:string"/>
    <!--child element of store_header-->
    <xs:element name="search_bar">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="search_text"/>
                <xs:element ref="search_icon"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!--child element of search_bar-->
    <xs:element name="search_icon">
        <xs:complexType>
            <xs:attribute ref="id" use="required"/>
        </xs:complexType>
    </xs:element>
    <!--child element of search_bar-->
    <xs:element name="search_text" type="xs:string"/>


    <!--child element of august_gift_store-->
    <xs:element name="store_details">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="store_description"/>
                <xs:element ref="store_intro"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
     
    <!--child element of store_details-->
    <xs:element name="store_description">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="description_header"/>
                <xs:element ref="description_label"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!--child element of store_description-->
    <xs:element name="description_header" type="xs:string"/>
    <!--child element of store_description-->
    <xs:element name="description_label">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:minLength value="35"/>
                <xs:maxLength value="150"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <!--child element of store_details-->
    <xs:element name="store_intro">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="store_name"/>
                <xs:element ref="store_address"/>
                <xs:element ref="store_telephone_number"/>
                <xs:element ref="store_website"/>
                <xs:element ref="store_email"/>
            </xs:sequence>
            <xs:attribute ref="intro" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:attribute name="intro" type="xs:string" fixed="about"/>
    <!--child element of store_intro-->
    <xs:element name="store_name" type="xs:string"/>
    <!--child element of store_intro-->
    <xs:element name="store_address">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute ref="location" use="optional"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:attribute name="location" type="xs:string" default="London"/>
    <!--child element of store_intro-->
    <xs:element name="store_telephone_number">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[0-9]{3}-[0-9]{3}-[0-9]{4}"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <!--child element of store_intro-->
    <xs:element name="store_website" type="xs:string"/>


    <!--child element of august_gift_store-->
    <xs:element name="brand_collaboration" type="xs:string"/>

    <xs:element name="store_email">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[^@]+@[^\.]+\..+"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>


    <!--child element of august_gift_store-->
    <xs:element name="brands">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="brand" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!--child element of brands-->
    <xs:element name="brand">
        <xs:complexType>
            <xs:attribute ref="id" use="required"/>
        </xs:complexType>
    </xs:element>


    <!--child element of august_gift_store-->
    <xs:element name="gift_cards">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="gift_card" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!--child element of gift_cards-->
    <xs:element name="gift_card">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="card_image"/>
                <xs:element ref="card_content"/>
            </xs:sequence>
            <xs:attribute ref="type" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="card_image">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="card_design"/>
                <xs:element ref="add_to_cart"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:attribute name="type">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Physical"/>
                <xs:enumeration value="Digital"/>
            </xs:restriction> 
        </xs:simpleType>
    </xs:attribute>

    <!--child element of gift_image-->
    <xs:element name="card_design">
        <xs:complexType>
            <xs:attribute ref="id" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="add_to_cart">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="cart_display"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="cart_display" type="xs:string"/>

    <!--child element of gift_card-->
    <xs:element name="card_content">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="card_name"/>
                <xs:element ref="card_type"/>
                <xs:element ref="card_cost"/>
                <xs:element ref="usable_amount"/>
                <xs:element ref="no_of_users"/>
                <xs:element ref="card_expiration_date"/>
                <xs:element ref="extendable_period" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="customizable"/>
                <xs:element ref="card_delivery" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="international_shipping" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="payment"/>
                <xs:element ref="refundable"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!--child elements of card_content-->
    <xs:element name="card_name">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute ref="card_id" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:attribute name="card_id" type="xs:IDREF"/>
    <xs:element name="card_type">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Physical"/>
                <xs:enumeration value="Digital"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="card_cost" type="xs:positiveInteger"/>
    <xs:element name="usable_amount" type="xs:positiveInteger"/>
    <xs:element name="no_of_users" type="xs:positiveInteger" fixed="1"/>
    
    <xs:element name="card_expiration_date">
        <xs:simpleType>
            <xs:restriction base="xs:date">
                <xs:minInclusive value="2021-03-01"/>
                <xs:maxExclusive value="2030-12-31"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="extendable_period">
        <xs:simpleType>
            <xs:restriction base="xs:positiveInteger">
                <xs:minInclusive value="1"/>
                <xs:maxInclusive value="12"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="customizable">
        <xs:complexType>
            <xs:all>
                <xs:element ref="customizable_header"/>
                <xs:element ref="customization_charge" minOccurs="0" maxOccurs="1"/>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="customizable_header">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Yes"/>
                <xs:enumeration value="No"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="customization_charge" type="xs:string"/>

    <xs:element name="card_delivery">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="delivery_header"/>
                <xs:element ref="delivery_charge"/>
                <xs:element ref="delivery_duration"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="delivery_header" type="xs:string"/>
    <xs:element name="delivery_charge" type="xs:positiveInteger"/>

    <xs:element name="delivery_duration">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:NMTOKEN">
                    <xs:attribute ref="tok_type" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>    
    </xs:element>
    <xs:attribute name="tok_type" type="xs:NMTOKEN"/>

    <xs:element name="international_shipping">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Available"/>
                <xs:enumeration value="Not Available"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="payment">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="payment_header"/>
                <xs:element ref="li" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="payment_header" type="xs:string"/>

    <xs:element name="li">
        <xs:complexType>
            <xs:all>
                <xs:element ref="payment_on_delivery" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="online_payment" minOccurs="0" maxOccurs="1"/>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="payment_on_delivery">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="availability">
                    <xs:attribute ref="availability"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="availability">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Available"/>
            <xs:enumeration value="Not Available"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:attribute name="availability">
        <xs:simpleType>
            <xs:restriction base="xs:boolean"/>
        </xs:simpleType>
    </xs:attribute>

    <xs:element name="online_payment" type="xs:string" fixed="Available"/>

    <xs:element name="refundable">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Refundable (conditions applied)"/>
                <xs:enumeration value="Not Refundable"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <!--child element of august_gift_store-->
    <xs:element name="page_footer">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="description"/>
                <xs:element ref="email"/>
                <xs:element ref="subscribe"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="description" type="xs:string"/>
    <xs:element name="email" type="xs:string"/>
    <xs:element name="subscribe" type="xs:string"/>

    
    <!--child element of august_gift_store-->
    <xs:element name="footer_info">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="store"/>
                <xs:element ref="terms"/>
                <xs:element ref="privacy"/>
                <xs:element ref="get_in_touch"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="store" type="xs:string"/>
    <xs:element name="terms" type="xs:string"/>
    <xs:element name="privacy" type="xs:string"/>
    <xs:element name="get_in_touch">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="title"/>
                <xs:element ref="footer_icons"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="title" type="xs:string"/>
    <xs:element name="footer_icons">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="icons" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="icons">
        <xs:complexType>
            <xs:attribute ref="id" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== sakss-g/xml/catalog_20049006.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!--linking css-->
<?xml-stylesheet href="catalog_20049006.css"?>

<!--declaring root element and linking schema-->
<august_gift_store xsi:noNamespaceSchemaLocation="catalog_20049006.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"> 
    <!--declaring elements for navigation bar of the web page-->
    <store_header>
        <store_logo id="L001"/>
        <nav_bar>
            <nav_element>Gift</nav_element>
            <nav_element>Brands</nav_element>
            <nav_element>Corporate</nav_element>
            <nav_element>Multi-Store</nav_element>
            <nav_element>Blog</nav_element>
            <nav_element>More</nav_element>
            <shopping_cart id="L002"/>
        </nav_bar>
        <sign_in>Sign In</sign_in>
        <search_bar>
            <search_text>Search</search_text> 
            <search_icon id="L003"/>
        </search_bar>
    </store_header>

    <!--declaring elements for the details about the store-->
    <store_details>
        <store_description>
            <description_header>Welcome !!</description_header>
            <description_label> <![CDATA[In celebrations and joys, shower your loved ones with bundle of happiness. Shop here at August's Gifts for some awesome gift cards.]]> </description_label>
        </store_description>
        
        <store_intro intro="about">
            <store_name>August's Gifts</store_name>
            <store_address location="London">London, Regent St., W1C 5TD.</store_address>
            <store_telephone_number>519-661-4965</store_telephone_number>
            <store_website>www.augustsgifts.com </store_website>
            <store_email>augustsgifts@gmail.com</store_email>
        </store_intro>
    </store_details>

    <!--declaring elements for brands whose gift card is available in the store-->
    <brand_collaboration>Brands in Collaboration</brand_collaboration>
    
    <brands>
        <brand id="C001"/>
        <brand id="C002"/>
        <brand id="C003"/>
        <brand id="C004"/>
        <brand id="C005"/>
        <brand id="C006"/>
    </brands>

    <!--each card is separated within the element gift_cards by the element gift_card-->
    <gift_cards>
        <!--Declaring child elements of the parent element gift_cards-->
        <gift_card type="Physical">
            <card_image>
                <card_design id="CD001"/>
                <add_to_cart>
                    <cart_display>Add to Cart</cart_display>
                </add_to_cart>   
            </card_image>
            <card_content>
                <card_name card_id="C001">H&amp;M Birthday Gift Card</card_name>
                <card_type>Physical</card_type>
                <card_cost>105</card_cost>
                <usable_amount>100</usable_amount>
                <no_of_users>1</no_of_users>
                <card_expiration_date>2022-12-12</card_expiration_date>
                <customizable>
                    <customizable_header>No</customizable_header>
                </customizable>
                <!--optional element for the parent element card_content is card_delivery-->
                <card_delivery>
                    <delivery_header/>
                    <delivery_charge>20</delivery_charge>
                    <delivery_duration tok_type="00-00">07-10</delivery_duration>
                </card_delivery>
                <!--optional element for the parent element card_content is international_shipping-->
                <international_shipping>Available</international_shipping>
                <payment>
                    <payment_header/>
                    <!--optional element for the parent element payment is payment_on_delivery-->
                    <li><payment_on_delivery availability="false">Not Available</payment_on_delivery></li>
                    <li><online_payment>Available</online_payment></li>
                </payment> 
                <refundable>Refundable (conditions applied)</refundable>   
            </card_content>
        </gift_card>

        <gift_card type="Digital">
            <card_image>
                <card_design id="CD002"/>
                <add_to_cart>
                    <cart_display>Add to Cart</cart_display>
                </add_to_cart>   
            </card_image>
            <card_content>
                <card_name card_id="C001">H&amp;M Thank You Gift Card</card_name>
                <card_type>Digital</card_type>
                <card_cost>55</card_cost>
                <usable_amount>50</usable_amount>
                <no_of_users>1</no_of_users>
                <card_expiration_date>2024-03-01</card_expiration_date>
                <extendable_period>4</extendable_period>
                <customizable>
                    <!--optional element for the parent element customizable is customization_charge-->
                    <customizable_header>Yes</customizable_header>
                    <customization_charge>Negotiable</customization_charge>
                </customizable>
                <payment>
                    <payment_header/>
                    <li><online_payment>Available</online_payment></li>
                </payment>
                <refundable>Not Refundable</refundable>   
            </card_content>
        </gift_card>

        <gift_card type="Digital">
            <card_image>
                <card_design id="CD003"/>
                <add_to_cart>
                    <cart_display>Add to Cart</cart_display>
                </add_to_cart>   
            </card_image>
            <card_content>
                <card_name card_id="C002">SHEIN - Never go out of style</card_name>
                <card_type>Digital</card_type>
                <card_cost>205</card_cost>
                <usable_amount>200</usable_amount>
                <no_of_users>1</no_of_users>
                <card_expiration_date>2022-11-12</card_expiration_date> 
                <extendable_period>5</extendable_period>
                <customizable>
                    <customizable_header>No</customizable_header>
                </customizable>
                <payment>
                    <payment_header/>
                    <li><online_payment>Available</online_payment></li>
                </payment> 
                <refundable>Not Refundable</refundable> 
            </card_content>  
        </gift_card>

        <gift_card type="Digital">
            <card_image>
                <card_design id="CD004"/>
                <add_to_cart>
                    <cart_display>Add to Cart</cart_display>
                </add_to_cart>   
            </card_image>
            <card_content>
                <card_name card_id="C002">SHEIN - Always in Trend</card_name>
                <card_type>Digital</card_type>
                <card_cost>105</card_cost>
                <usable_amount>100</usable_amount>
                <no_of_users>1</no_of_users>
                <card_expiration_date>2023-11-12</card_expiration_date>   
                <extendable_period>3</extendable_period>
                <customizable>
                    <customizable_header>No</customizable_header>
                </customizable>
                <payment>
                    <payment_header/>
                    <li><online_payment>Available</online_payment></li>
                </payment> 
            <refundable>Not Refundable</refundable>   
            </card_content>
        </gift_card>

        <gift_card type="Digital">
            <card_image>
                <card_design id="CD005"/>
                <add_to_cart>
                    <cart_display>Add to Cart</cart_display>
                </add_to_cart>   
            </card_image>
            <card_content>
                <card_name card_id="C003">amazon - congratulations card</card_name>
                <card_type>Digital</card_type>
                <card_cost>55</card_cost>
                <usable_amount>50</usable_amount>
                <no_of_users>1</no_of_users>
                <card_expiration_date>2023-05-06</card_expiration_date>
                <extendable_period>6</extendable_period>
                <customizable>
                    <customizable_header>No</customizable_header>
                </customizable>
                <payment>
                    <payment_header/>
                    <li><online_payment>Available</online_payment></li>
                </payment> 
                <refundable>Not Refundable</refundable>   
            </card_content>
        </gift_card>

        <gift_card type="Physical">
            <card_image>
                <card_design id="CD006"/>
                <add_to_cart>
                    <cart_display>Add to Cart</cart_display>
                </add_to_cart>   
            </card_image>
            <card_content>
                <card_name card_id="C003">amazon - Mother's Day card</card_name>
                <card_type>Physical</card_type>
                <card_cost>55</card_cost>
                <usable_amount>50</usable_amount>
                <no_of_users>1</no_of_users>
                <card_expiration_date>2024-05-24</card_expiration_date>
                <customizable>
                    <customizable_header>No</customizable_header>
                </customizable>
                <!--optional element for the parent element card_content is card_delivery-->
                <card_delivery>
                    <delivery_header/>
                    <delivery_charge>10</delivery_charge>
                    <delivery_duration tok_type="00-00">07-10</delivery_duration>
                </card_delivery>
                <!--optional element for the parent element card_content is international_shipping-->
                <international_shipping>Not Available</international_shipping>
                <payment>
                    <payment_header/>
                    <!--optional element for the parent element payment is payment_on_delivery-->
